### ISSUE TITLE
https://wiki.info-ops.org links don't work

### ISSUE THREAD

**Issue by GitMje** [DanielBMarkham/ea#1]
This looks like a promising tool, but the https://wiki.info-ops.org/index.php/EasyAM_2_Language_Spec?ref=wiki link doesn't work.

**Comment by DanielBMarkham** [comment]
Apologies. I took down my permanent server on the net a while back and that meant I couldn't keep the wiki alive. My plans are to replace it at some point but I'm not sure exactly how that will happen, so I can't update the text/links.

Meanwhile, if you're serious about this topic and definitely before you touch or start using the code in a serious way, [read the books.](https://leanpub.com/u/DanielBMarkham)

If you're just skimming and doing some tire-kicking, there's a nice video overview of [EasyAM here]( https://danielbmarkham.locals.com/post/133970/theory-tuesdays-easy-analysis-compiler) I did a few months ago.

And if you'd like to be part of a larger ongoing conversation about the Info-Ops concepts and how they related to a lot of social and technical news, I have a [locals channel that contains new stuff every day.](https://danielbmarkham.locals.com/) There are 5-10 videos already on here explaining the theory and demonstrating some of the various things you can do. For instance, I was just [talking about using the EasyAM output as part of Test-Driven Infrastructure last week.](https://danielbmarkham.locals.com/post/224716/test-driven-infrastructure) *Note that some material, but not most material, on my channel is for supporters-only. This is usually material that's not ready for prime-time or may be controversial in some way.*

I will try to resolve and close this issue over the next few months. There was a lot of detailed and freely-available material on the wiki that I definitely want to be available to anybody that's interested.

**Comment by DanielBMarkham** [comment]
I am standing up a new wiki at https://wiki.info-ops.org/index.php/EasyAM

I will close this ticket in a week or two when there's enough information over there to justify replacing all of the links.

**Comment by DanielBMarkham** [comment]
I've done enough on standing up the new wiki that I'm going to mark this done. Thanks again for the heads-up
